version: "2.1"
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@5.1.0
  python: circleci/python@2.1.1

jobs:
  # say_hello:
  #   executor: python/default
  #   steps:
  #     - run: echo "Hello world!"
  build_flask_app:
    description: "Setup Flask App"
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip

  # build_vite_app:
  #   executor: node/default
  #   steps:
  #     - checkout
  #     - run: cd client
  #     - run: sudo npm install -g npm@latest
  #     - node/install-packages:
  #         cache-path: ~/project/node_modules
  #         override-ci-command: npm install
  #     - node/run:
  #         npm-run: build

workflows:
  main:
    jobs:
      # - say_hello
      - build_flask_app
      - eb/deploy:
          context: aws-credentials
          application-name: MeowAI
          environment-name: MeowAI
          platform-version: python-3.7
          requires:
            - build_flask_app
      # - build_vite_app
