version: "2.1"
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@5.1.0
  python: circleci/python@2.1.1
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  build_flask_app:
    description: "Setup Flask App"
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip

  build_vite_app:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Build App
          command: |
            cd client/
            npm install
            npm run build
            ls -al dist
            cd dist
      - run:
          name: Install Elastic Beanstalk
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli
      - aws-cli/setup:
          aws-region: aws_region
          aws-access-key-id: aws_access_key_id
          aws-secret-access-key: aws_secret_access_key
      - run:
          name: Deploy
          command: |
            eb init MeowAI-Page -p php
            eb create MeowAI-Page
            eb deploy MeowAI-Page

workflows:
  deploy-api:
  jobs:
    - build_flask_app
    - eb/deploy:
        context: aws-credentials
        environment-name: MeowAI
        platform-version: python-3.7
        filters:
          branches:
            only:
              - flask_eb
        label: version-<<pipeline.number>>
        requires:
          - build_flask_app
  # deploy-app:
  #   jobs:
  #     - build_vite_app
