version: "2.1"
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@5.1.0
  python: circleci/python@2.1.1

jobs:
  say_hello:
    steps:
      - run: echo "Hello world!"
  # build_flask_app:
  #   executor: python/default
  #   steps:
  #     - checkout
  #     - python/install-packages:
  #         pkg-manager: pip
  #     - python/install-packages:
  #         pip-dependency-file: requirements.txt
  #         pkg-manager: pip
  #     - python/install-packages:
  #         args: pytest
  #         pkg-manager: pip
  #         pypi-cache: false
  #     - run:
  #         command: |
  #           pytest --version
  #         name: Test
  # build_vite_app:
  #   executor: node/default
  #   steps:
  #     - checkout
  #     - run: cd client
  #     - run: sudo npm install -g npm@latest
  #     - node/install-packages:
  #         cache-path: ~/project/node_modules
  #         override-ci-command: npm install
  #     - node/run:
  #         npm-run: build

workflows:
  main:
    jobs:
      - say_hello
      # - build_flask_app
      # - build_vite_app
